> library(readr)
> hate_crimes <- read_csv("Downloads/ps4_data/hate_crimes.csv")
> View(hate_crimes)
> which.max(hate_crimes$avg_hatecrimes_per_100k_fbi)
> hate_crimes$state[9]
> plot(hate_crimes$gini_index,hate_crimes$avg_hatecrimes_per_100k_fbi)
> cleaned <- na.omit(hate_crimes, cols = c(gini_index,avg_hatecrimes_per_100k_fb))
> cor(cleaned$gini_index,cleaned$avg_hatecrimes_per_100k_fbi)
> reg <- lm(avg_hatecrimes_per_100k_fbi ~ gini_index, data = hate_crimes)
> summary(reg)
> plot(hate_crimes$gini_index,hate_crimes$avg_hatecrimes_per_100k_fbi)
> abline(reg)
> text(hate_crimes$gini_index, hate_crimes$avg_hatecrimes_per_100k_fbi, hate_crimes$state, cex=.5)
> options(scipen=999)
> reg2 <- lm(avg_hatecrimes_per_100k_fbi ~ median_household_income+share_unemployed_seasonal+gini_index+share_population_with_high_school_degree+share_non_white, data = hate_crimes)
> summary(reg2)
> library(readr)
> democracy <- read_csv("Downloads/ps4_data/democracy.csv")
> (uniqueRegion <- unique(c(democracy$regions)))
> ave06 <- rep(NA, length(uniqueRegion))
> ave16 <- rep(NA, length(uniqueRegion))
> for(i in 1:length(uniqueRegion)) {
  + ave06[i] <- mean(democracy$dem_score_2006[as.character(democracy$regions) == uniqueRegion[i]], na.rm = TRUE)
  + ave16[i] <- mean(democracy$dem_score_2016[as.character(democracy$regions) == uniqueRegion[i]], na.rm = TRUE)
  + }
> (ave06)
